name: Pollen.jl build - dev

on:
  push:
    branches: [$default-branch, 'lo/pollen-actions']

jobs:
  pollen:
    name: "Pollen - Build documentation on push to main"
    runs-on: ubuntu-latest
    steps:
      - uses: "lorenzoh/Pollen.jl@lo-develop/.github/workflows/pollen.yml"
        with:
          tag: dev
