name: Pollen.jl build - dev

on:
  push:
    branches: [$default-branch, "lo/pollen-actions"]


jobs:
  pollen:
    name: "Pollen - Build documentation on push to main"
    uses: "./.github/workflows/pollen.build.yml"
    with:
      tag: dev
    secrets:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
